services:
  sensible:
    restart: always
    image: ghcr.io/mpepping/docker-sensible:latest
    network_mode: host
    volumes:
      - ./settings.yaml:/etc/sensible/settings.yaml
      - /etc:/host/etc:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
